  Error in file name !!!
  Number of VES locations more then possible !!!
  Max. possible number of VES curves =
  Number of AB/2 on profile more then possible !!!
  Max. possible number of AB/2 =
  I/O error in AB/2 values !!!
  First AB/2 is less then 0.001 !!!
  AB/2 value N
 is less then previous one !!!
  I/O error in the name VES N :
  Unexpected end of file !!!
  Number of AB/2 more then possible !!!
  Max. number of AB/2 on profile =
  I/O error in the field data this VES location
  Rho_a value N =
  is wrong !!!
  Eta_a value N =
  is wrong !!!
  Wrong name or wrong position of model in *.res file !!!
  Layers number more then possible !!!
  Max. possible layers number =
  I/O error by reading model  !!!
  I/O error by reading profile Keys !!!
  Read instruction !!!
  "IPI_GATE" program is only for VES not for IP !!!
  Too many segments on VES curve !!!
  (Max number of segments - 1) =
  Key of array may be one of next figures { -4, -3, 0, 3, 4 } !!!
  Read instruction !!!
  Length of MN line N
 less then 0.001 !!!
  I/O error in Current value (for profile) !!!
  Current value is less then 1.0E-12 !!!
  I/O error in Current value for measurement N 
  Current value for measurement N 
 is less then 1.0E-12 . Correct it !!!
  Number of distance value for segment N
 is more then total number of distances !!!
  Correct resistivity value for layer N =
  Correct Thickness value for layer N =
  Correct Chargeability value for layer N =
   !!!
  X-coordinate value N
 is less then previous one !!!
  I/O error in X-coordinate value N
  I/O error in Z-coordinate value N        
  Key for altitude of VES points should be from 0 to 2 !!!
  After X-coordinate line should be character '+' in separate line !!!
  This version is without IP-mode.
  If You need it - tell me!   boba@geophys.geol.msu.ru
